services:
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: no
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '9080:80'
      # Change the number before : to the port the SMTP server should be accessible on
      - '9025:25'
